name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Start server
        run: |
          npm run server
          echo "Waiting for server to be ready..."
          until curl -s http://localhost:3000/; do sleep 1; done
        env:
          NODE_ENV: test
        
      - name: Set up k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 tests
        run: npm run test